// frontend/src/features/auth/OwnerAccessGate.tsx
import { useState, type ReactNode } from 'react';
import type { UseAuth } from './useAuth';

export function OwnerAccessGate({
  auth,
  children,
}: {
  auth: UseAuth;
  children: ReactNode;
}) {
  const [adminToken, setAdminToken] = useState('');
  const [claiming, setClaiming] = useState(false);
  const [claimError, setClaimError] = useState<string | null>(null);

  if (auth.loading) {
    return (
      <section className="panel mx-auto max-w-2xl p-6 text-center" data-testid="owner-access-loading">
        <p className="font-mono text-sm text-silver-dk">Checking owner access…</p>
      </section>
    );
  }

  if (!auth.authenticated) {
    return (
      <section className="panel mx-auto max-w-2xl space-y-4 p-6" data-testid="owner-sign-in-required">
        <h2 className="font-display text-lg tracking-[0.14em] text-orange">Owner sign-in required</h2>
        <p className="text-sm leading-relaxed text-silver-dk">
          Operational dashboards and health information are private. Sign in with the Frontier account linked to ED-Finder.
        </p>
        <button type="button" onClick={auth.signIn} className="btn-primary px-4 py-2">
          Sign in with Frontier
        </button>
      </section>
    );
  }

  if (!auth.user?.is_owner) {
    return (
      <section className="panel mx-auto max-w-2xl space-y-4 p-6" data-testid="owner-access-denied">
        <h2 className="font-display text-lg tracking-[0.14em] text-orange">Owner access only</h2>
        <p className="text-sm leading-relaxed text-silver-dk">
          This Frontier account is signed in, but it is not linked as ED-Finder’s owner.
        </p>
        {auth.ownerClaimAvailable ? (
          <div className="premium-subpanel space-y-3 p-4">
            <p className="text-xs leading-relaxed text-silver-dk">
              First-time setup: enter the existing ED-Finder admin token once to link this Frontier account as the owner.
            </p>
            <div className="flex flex-wrap gap-2">
              <input
                type="password"
                value={adminToken}
                onChange={(event) => setAdminToken(event.target.value)}
                placeholder="Existing admin token"
                data-testid="owner-claim-token"
                className="min-w-[220px] flex-1"
                autoComplete="off"
              />
              <button
                type="button"
                disabled={!adminToken.trim() || claiming}
                data-testid="owner-claim-submit"
                className="btn-primary px-4 py-2 disabled:cursor-not-allowed disabled:opacity-40"
                onClick={() => {
                  setClaiming(true);
                  setClaimError(null);
                  void auth.claimOwner(adminToken.trim())
                    .then(() => setAdminToken(''))
                    .catch((caught: unknown) => {
                      setClaimError(caught instanceof Error ? caught.message : String(caught));
                    })
                    .finally(() => setClaiming(false));
                }}
              >
                {claiming ? 'Linking…' : 'Link owner account'}
              </button>
            </div>
            {claimError ? <p className="text-xs text-red">{claimError}</p> : null}
          </div>
        ) : null}
        <button type="button" onClick={() => void auth.signOut()} className="btn-metal px-4 py-2">
          Sign out
        </button>
      </section>
    );
  }

  return children;
}

// apps/web/src/lib/components/OwnerAccessGate.svelte
<script lang="ts">
  import type { AuthState } from '$lib/auth/auth';
  let { authState, signIn, signOut, claimOwner, children } = $props<{
    authState: AuthState;
    signIn: () => void;
    signOut: () => Promise<void>;
    claimOwner: (token: string) => Promise<void>;
    children: import('svelte').Snippet;
  }>();
  let token = $state('');
  let claiming = $state(false);
  let claimError = $state<string | null>(null);
  async function claim() {
    claiming = true;
    claimError = null;
    try {
      await claimOwner(token);
      token = '';
    } catch (error) {
      claimError = error instanceof Error ? error.message : String(error);
    } finally {
      claiming = false;
    }
  }
</script>

{#if authState.loading}
  <section class="panel gate" data-testid="owner-access-loading">
    <p aria-live="polite">Checking owner access…</p>
  </section>
{:else if !authState.authenticated}
  <section class="panel gate" data-testid="owner-sign-in-required">
    <h1>Owner sign-in required</h1>
    <p>
      Operational dashboards and health information are private. Sign in with
      the Frontier account linked to ED-Finder.
    </p>
    <button type="button" onclick={signIn}>Sign in with Frontier</button>
  </section>
{:else if !authState.user?.is_owner}
  <section class="panel gate" data-testid="owner-access-denied">
    <h1>Owner access only</h1>
    <p>
      This Frontier account is signed in, but it is not linked as ED-Finder’s
      owner.
    </p>
    {#if authState.ownerClaimAvailable}
      <form
        onsubmit={(event) => {
          event.preventDefault();
          void claim();
        }}
      >
        <label for="owner-token">Existing ED-Finder admin token</label>
        <input
          id="owner-token"
          type="password"
          bind:value={token}
          autocomplete="off"
          data-testid="owner-claim-token"
        />
        <button
          type="submit"
          disabled={!token.trim() || claiming}
          data-testid="owner-claim-submit"
          >{claiming ? 'Linking…' : 'Link owner account'}</button
        >
      </form>
      {#if claimError}<p role="alert">{claimError}</p>{/if}
    {/if}
    <button type="button" onclick={() => void signOut()}>Sign out</button>
  </section>
{:else}
  {@render children()}
{/if}
